[package]
authors = ["David LeGare <excaliburhissheath@gmail.com>"]
name = "hangry-hippos"
version = "0.1.0"

[dependencies]
rouille = "1.0.1"
serde = "1.0.8"
serde_derive = "1.0.8"
serde_json = "1.0.2"
